spring:

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://jdbc:postgresql://dpg-d5rkp615pdvs739qqco0-a.frankfurt-postgres.render.com:5432/grandsmartchefdb?sslmode=require}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:uck1aQzzyN8rH27GfMcz0sx2pdIMKIvh}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


application:
  storage:
    profile-photos: /data/uploads/profile
  security:
    jwt:
      secret-key: NzY4ZjI2MTMxZjg0ZjU5MWQzNjE2ZjQ1ZThkZGI5NGE3NDcyZjRmMTY2ZjQ5NzUw
      expiration-ms: 3600000

